#!/usr/bin/env node
/**
 * Writes packages/web/dist into a TypeScript module the binary can carry.
 *
 * The compiled binary has no dist directory next to it, so the release build inlines
 * every asset as base64 and the server prefers that copy over the disk. Run after the
 * web build and before `bun build --compile`.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = resolve(root, "packages/web/dist");
const out = resolve(root, "packages/server/src/generated/web-assets.ts");

function walk(dir) {
  const found = [];
  for (const name of readdirSync(dir)) {
    const abs = join(dir, name);
    if (statSync(abs).isDirectory()) found.push(...walk(abs));
    else found.push(abs);
  }
  return found;
}

let files;
try {
  files = walk(dist);
} catch {
  console.error(`embed-web: ${dist} does not exist. Run the web build first.`);
  process.exit(1);
}

// Source maps are for a developer with the repo open, not for a shipped binary.
const shipped = files.filter((f) => !f.endsWith(".map"));
if (shipped.length === 0) {
  console.error(`embed-web: ${dist} is empty. Run the web build first.`);
  process.exit(1);
}

const entries = shipped
  .map((abs) => [relative(dist, abs).split("\\").join("/"), readFileSync(abs)])
  .sort(([a], [b]) => (a < b ? -1 : 1));

const body = entries
  .map(([name, buf]) => `  ${JSON.stringify(name)}: ${JSON.stringify(buf.toString("base64"))},`)
  .join("\n");

writeFileSync(
  out,
  `/**
 * The web build, embedded in the binary.
 *
 * Generated by scripts/embed-web.mjs. Do not edit by hand.
 */
export const EMBEDDED_WEB_ASSETS: Readonly<Record<string, string>> = {
${body}
};
`,
  "utf8",
);

const bytes = entries.reduce((n, [, buf]) => n + buf.byteLength, 0);
console.log(`embed-web: ${entries.length} files, ${(bytes / 1024).toFixed(0)} kB -> ${relative(root, out)}`);
